name: isce3_rtc
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - isce3>=0.14.0
  - gdal>=3.0
  - h5py>=3.0
  - matplotlib-base
  - numpy>=1.20
  - pyre>=1.11.2
  - pyproj>=3.3
  - ruamel.yaml
  - scipy!=1.10.0
  - setuptools
  - shapely
  - yamale
  - s1reader
